[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore:'crypt' is deprecated and slated for removal in Python 3.13:DeprecationWarning:passlib.utils
    ignore:The 'app' shortcut is now deprecated.*:DeprecationWarning:httpx._client
    ignore:datetime.datetime.utcnow\(\) is deprecated and scheduled for removal in a future version.*:DeprecationWarning:jose.jwt
