"""03_update reviews

Revision ID: 1a473f7d1dd1
Revises: e50b757963eb
Create Date: 2025-01-29 07:04:09.880131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a473f7d1dd1'
down_revision: Union[str, None] = 'e50b757963eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_reviews', 'last_modified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最終更新日時(Program)',
               existing_comment='最終更新日時',
               existing_nullable=False)
    op.create_index(op.f('ix_book_reviews_last_modified_at'), 'book_reviews', ['last_modified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_reviews_last_modified_at'), table_name='book_reviews')
    op.alter_column('book_reviews', 'last_modified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最終更新日時',
               existing_comment='最終更新日時(Program)',
               existing_nullable=False)
    # ### end Alembic commands ###
